// Browser regression checks use an isolated backend, vault and repositories. Never the live app.
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { chromium } from 'playwright';
import { testBackend } from './test-backend.mjs';
const fixture = await testBackend(); const errors = []; const out = new URL('../output/playwright/', import.meta.url).pathname; mkdirSync(out, { recursive: true });
let browser;
try {
  browser = await chromium.launch({ channel: process.env.CI ? undefined : 'chrome' });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && !(message.location().url.endsWith('/api/commands') && message.text().includes('400'))) errors.push(message.text() + ' @ ' + message.location().url); });
  await page.goto(fixture.base + '/?nosw=1');
  await page.waitForFunction(() => window.nibbiApp && document.body.dataset.link === 'live');
  assert.equal((await (await fetch(fixture.base + '/api/fixers')).json()).length, 15, 'No twelve-run truncation');
  await page.screenshot({ path: out + 'desktop.png' });
  await page.evaluate(() => { document.querySelector('#st-platform').click(); });
  await page.getByRole('dialog').waitFor();
  await page.getByText('No API key is required.', { exact: false }).waitFor();
  // Exercise the controls without invoking a real login or querying user accounts.
  await page.route('**/api/providers', route => route.fulfill({ json: { claude: { connected: true, mode: 'signin', subscription: 'max' }, codex: { connected: false } } }));
  await page.route('**/api/providers/claude/login', route => { assert.equal(route.request().method(), 'POST'); return route.fulfill({ json: { message: 'Fixture sign-in handoff. Complete it, then Check connections.' } }); });
  await page.getByRole('button', { name: 'Check connections', exact: true }).click();
  await page.getByText('Claude: signed in · max', { exact: false }).waitFor();
  await page.getByRole('button', { name: 'Sign in with Claude', exact: true }).click();
  await page.getByText('Fixture sign-in handoff.', { exact: false }).waitFor();
  await page.screenshot({ path: out + 'providers.png' });
  await page.getByRole('button', { name: 'Skills', exact: true }).click();
  await page.getByText('nibbi-fixer-brief', { exact: false }).first().waitFor();
  const lead = page.locator('fieldset').filter({ has: page.locator('legend', { hasText: /^lead$/ }) });
  await lead.getByRole('checkbox').first().check();
  await lead.getByRole('button', { name: 'Save lead skills', exact: true }).click();
  await page.getByText('Saved pinned revisions for the next run.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Inspect nibbi-fixer-brief', exact: true }).click();
  await page.getByRole('combobox', { name: 'Skill package file' }).waitFor();
  await page.screenshot({ path: out + 'skills.png' });
  await page.getByRole('button', { name: 'Vault', exact: true }).click();
  await page.getByRole('button', { name: 'MEMORY.md', exact: true }).click();
  await page.getByText('A private, temporary test vault.', { exact: false }).waitFor();
  await page.getByRole('button', { name: 'Schedules', exact: true }).click();
  await page.getByRole('button', { name: 'Enable', exact: true }).first().waitFor();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.evaluate(() => window.nibbiApp.send('/project fixture'));
  await page.waitForFunction(() => !window.nibbiApp.state().busy);
  await page.evaluate(() => window.nibbiApp.send('/goal finish M1'));
  const goal = await (await fetch(fixture.base + '/nibbi/goal')).json(); assert.equal(goal.fixture.focus, 'M1: Fixture'); assert.equal(goal.fixture.mode, 'stage');
  await page.evaluate(() => window.nibbiApp.send('/goal stop'));
  assert.equal((await (await fetch(fixture.base + '/api/auto')).json()).fixture.on, false, 'Stopping a goal disables auto');
  await page.evaluate(() => window.nibbiApp.send('/review'));
  await page.locator('.rhead').waitFor();
  // Make the diff available in the UI without changing the unverified merge gate.
  const before = await page.locator('.rhead').textContent();
  await page.getByRole('button', { name: 'approve & merge (a)', exact: true }).click();
  await page.getByRole('button', { name: 'merge — sure?', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#toast')?.textContent.includes('verified'));
  assert.equal(await page.locator('.rhead').textContent(), before, 'Failed merge keeps the item in review');
  const forbidden = await fetch(fixture.base + '/api/commands', { method: 'POST', headers: { 'content-type': 'application/json', Origin: 'https://untrusted.example' }, body: '{}' });
  assert.equal(forbidden.status, 403, 'Cross-origin mutations are rejected');
  const key = crypto.randomUUID(); const command = { name: 'run.discard', idempotencyKey: key, args: { id: 'fixture-0' } };
  const once = await (await fetch(fixture.base + '/api/commands', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(command) })).json();
  const twice = await (await fetch(fixture.base + '/api/commands', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(command) })).json();
  assert.deepEqual(once, twice, 'Repeated commands have one result');
  const cursor = (await (await fetch(fixture.base + '/api/snapshot')).json()).cursor;
  const replay = await fetch(fixture.base + '/api/events?after=' + (cursor - 1)); const reader = replay.body.getReader(); const chunk = new TextDecoder().decode((await reader.read()).value); await reader.cancel();
  assert.match(chunk, new RegExp('id: ' + cursor + '\\n'), 'Events replay after the saved cursor');
  await context.close();
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const phone = await mobile.newPage(); phone.on('pageerror', error => errors.push(error.message)); await phone.goto(fixture.base + '/?nosw=1');
  await phone.waitForFunction(() => !!window.nibbiApp); await phone.evaluate(() => document.querySelector('#st-platform').click());
  await phone.getByRole('button', { name: 'Phone', exact: true }).click();
  await phone.getByRole('button', { name: 'Generate one-use pairing code', exact: true }).waitFor();
  await phone.screenshot({ path: out + 'phone.png' });
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No horizontal overflow on phone');
  await mobile.close();
  assert.deepEqual(errors, [], 'No unexpected browser errors');
  console.log('Browser checks passed: desktop, phone, Claude sign-in controls, skill activation/inspection, vault, schedules, stage-only goals, failed-review retention, event replay, idempotency and origin protection.');
} finally { await browser?.close(); await fixture.close(); }
